//NOT IN USE


const char ssl_ca_cert[] PROGMEM = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIFKDCCBM6gAwIBAgIQC9JZWvfkeVKsGBwPw1rxijAKBggqhkjOPQQDAjBKMQsw\n" \
"CQYDVQQGEwJVUzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEgMB4GA1UEAxMX\n" \
"Q2xvdWRmbGFyZSBJbmMgRUNDIENBLTMwHhcNMjIxMDE4MDAwMDAwWhcNMjMxMDE3\n" \
"MjM1OTU5WjByMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQG\n" \
"A1UEBxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEb\n" \
"MBkGA1UEAxMSb25kaWdpdGFsb2NlYW4uYXBwMFkwEwYHKoZIzj0CAQYIKoZIzj0D\n" \
"AQcDQgAEG2J2Mkx1pbnMhx86dX07Wm5B/AS7nu6sBQF/jVsS4mFM921Jyvs0VkY1\n" \
"6mjd/sya1UniE67v0hU3Bm7Agz3wiqOCA2wwggNoMB8GA1UdIwQYMBaAFKXON+rr\n" \
"sHUOlGeItEX62SQQh5YfMB0GA1UdDgQWBBTwtTLhT9RIInPJ2O8wgf3L8w1YUTAz\n" \
"BgNVHREELDAqghJvbmRpZ2l0YWxvY2Vhbi5hcHCCFCoub25kaWdpdGFsb2NlYW4u\n" \
"YXBwMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH\n" \
"AwIwewYDVR0fBHQwcjA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0Ns\n" \
"b3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA3oDWgM4YxaHR0cDovL2NybDQuZGlnaWNl\n" \
"cnQuY29tL0Nsb3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA+BgNVHSAENzA1MDMGBmeB\n" \
"DAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMw\n" \
"dgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy\n" \
"dC5jb20wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9D\n" \
"bG91ZGZsYXJlSW5jRUNDQ0EtMy5jcnQwDAYDVR0TAQH/BAIwADCCAX0GCisGAQQB\n" \
"1nkCBAIEggFtBIIBaQFnAHYArfe++nz/EMiLnT2cHj4YarRnKV3PsQwkyoWGNOvc\n" \
"gooAAAGD621qbQAABAMARzBFAiAq/9p/XhHp0ze8wB9FGH/kAcvWWa6zIbw2Mrgs\n" \
"BKRvZAIhAIgEjRPSTrgp1rJh8B5BVnFh49PLsO7QB2YWMWgKw2r3AHUAs3N3B+GE\n" \
"UPhjhtYFqdwRCUp5LbFnDAuH3PADDnk2pZoAAAGD621qYgAABAMARjBEAiAF7pOX\n" \
"CSyzZzI3vUEd6RdtgvQDrajsXlXYEkWzVlIr3AIgGvtUx6cR9jtRGhA1dCeoqS+X\n" \
"IjtThubFKzPlke7cRQkAdgC3Pvsk35xNunXyOcW6WPRsXfxCz3qfNcSeHQmBJe20\n" \
"mQAAAYPrbWowAAAEAwBHMEUCIQDi/0ilqEur3PhRvpia+OZd6kXU//jUgB8Co9Aj\n" \
"UihYOAIgMPrdZr0yOz2LKrQD6I5YKmgRafnm7oyEtySAYOqki9IwCgYIKoZIzj0E\n" \
"AwIDSAAwRQIhANOy4eAzudci/3h2VoEoOboscJJSkUu/54A7gqF1tNdpAiB0pNHU\n" \
"biUPQMCvLXuL2J2QhjbvfklJObDsrmNh1uO3nA==\n" \
"-----END CERTIFICATE-----\n";